// ============================================================
// DATOS PARA EL JUEGO MENTIROSO
// ============================================================

export const CATEGORIAS = [
  { key: 'selecciones', label: 'Selecciones' },
  { key: 'clubes', label: 'Clubes' },
  { key: 'jugadores', label: 'Jugadores' },
]

// ============================================================
// SELECCIONES NACIONALES
// ============================================================
export const SELECCIONES = [
  { nombre: 'España', grupo: 'Europa' },
  { nombre: 'Francia', grupo: 'Europa' },
  { nombre: 'Inglaterra', grupo: 'Europa' },
  { nombre: 'Alemania', grupo: 'Europa' },
  { nombre: 'Portugal', grupo: 'Europa' },
  { nombre: 'Italia', grupo: 'Europa' },
  { nombre: 'Paises Bajos', grupo: 'Europa' },
  { nombre: 'Belgica', grupo: 'Europa' },
  { nombre: 'Croacia', grupo: 'Europa' },
  { nombre: 'Dinamarca', grupo: 'Europa' },
  { nombre: 'Suiza', grupo: 'Europa' },
  { nombre: 'Turquia', grupo: 'Europa' },
  { nombre: 'Serbia', grupo: 'Europa' },
  { nombre: 'Polonia', grupo: 'Europa' },
  { nombre: 'Austria', grupo: 'Europa' },
  { nombre: 'Suecia', grupo: 'Europa' },
  { nombre: 'Noruega', grupo: 'Europa' },
  { nombre: 'Republica Checa', grupo: 'Europa' },
  { nombre: 'Hungria', grupo: 'Europa' },
  { nombre: 'Escocia', grupo: 'Europa' },
  { nombre: 'Rumania', grupo: 'Europa' },
  { nombre: 'Ucrania', grupo: 'Europa' },
  { nombre: 'Grecia', grupo: 'Europa' },
  { nombre: 'Brasil', grupo: 'Sudamerica' },
  { nombre: 'Argentina', grupo: 'Sudamerica' },
  { nombre: 'Uruguay', grupo: 'Sudamerica' },
  { nombre: 'Colombia', grupo: 'Sudamerica' },
  { nombre: 'Ecuador', grupo: 'Sudamerica' },
  { nombre: 'Chile', grupo: 'Sudamerica' },
  { nombre: 'Venezuela', grupo: 'Sudamerica' },
  { nombre: 'Paraguay', grupo: 'Sudamerica' },
  { nombre: 'Peru', grupo: 'Sudamerica' },
  { nombre: 'Bolivia', grupo: 'Sudamerica' },
  { nombre: 'Mexico', grupo: 'CONCACAF' },
  { nombre: 'Estados Unidos', grupo: 'CONCACAF' },
  { nombre: 'Canada', grupo: 'CONCACAF' },
  { nombre: 'Costa Rica', grupo: 'CONCACAF' },
  { nombre: 'Panama', grupo: 'CONCACAF' },
  { nombre: 'Honduras', grupo: 'CONCACAF' },
  { nombre: 'Jamaica', grupo: 'CONCACAF' },
  { nombre: 'Marruecos', grupo: 'Africa' },
  { nombre: 'Senegal', grupo: 'Africa' },
  { nombre: 'Nigeria', grupo: 'Africa' },
  { nombre: 'Ghana', grupo: 'Africa' },
  { nombre: 'Costa de Marfil', grupo: 'Africa' },
  { nombre: 'Camerun', grupo: 'Africa' },
  { nombre: 'Egipto', grupo: 'Africa' },
  { nombre: 'Tunisia', grupo: 'Africa' },
  { nombre: 'Argelia', grupo: 'Africa' },
  { nombre: 'Japon', grupo: 'Asia' },
  { nombre: 'Corea del Sur', grupo: 'Asia' },
  { nombre: 'Australia', grupo: 'Asia' },
  { nombre: 'Iran', grupo: 'Asia' },
  { nombre: 'Arabia Saudi', grupo: 'Asia' },
  { nombre: 'Qatar', grupo: 'Asia' },
]

// ============================================================
// CLUBES
// ============================================================
export const CLUBES = [
  { nombre: 'Real Madrid', liga: 'LaLiga' },
  { nombre: 'Barcelona', liga: 'LaLiga' },
  { nombre: 'Atletico de Madrid', liga: 'LaLiga' },
  { nombre: 'Athletic Club', liga: 'LaLiga' },
  { nombre: 'Real Sociedad', liga: 'LaLiga' },
  { nombre: 'Villarreal', liga: 'LaLiga' },
  { nombre: 'Sevilla', liga: 'LaLiga' },
  { nombre: 'Valencia', liga: 'LaLiga' },
  { nombre: 'Real Betis', liga: 'LaLiga' },
  { nombre: 'Celta de Vigo', liga: 'LaLiga' },
  { nombre: 'Osasuna', liga: 'LaLiga' },
  { nombre: 'Girona', liga: 'LaLiga' },
  { nombre: 'Manchester City', liga: 'Premier League' },
  { nombre: 'Arsenal', liga: 'Premier League' },
  { nombre: 'Liverpool', liga: 'Premier League' },
  { nombre: 'Chelsea', liga: 'Premier League' },
  { nombre: 'Manchester United', liga: 'Premier League' },
  { nombre: 'Tottenham', liga: 'Premier League' },
  { nombre: 'Newcastle', liga: 'Premier League' },
  { nombre: 'Aston Villa', liga: 'Premier League' },
  { nombre: 'Leicester City', liga: 'Premier League' },
  { nombre: 'West Ham United', liga: 'Premier League' },
  { nombre: 'Everton', liga: 'Premier League' },
  { nombre: 'Inter de Milan', liga: 'Serie A' },
  { nombre: 'AC Milan', liga: 'Serie A' },
  { nombre: 'Juventus', liga: 'Serie A' },
  { nombre: 'Napoles', liga: 'Serie A' },
  { nombre: 'AS Roma', liga: 'Serie A' },
  { nombre: 'Lazio', liga: 'Serie A' },
  { nombre: 'Fiorentina', liga: 'Serie A' },
  { nombre: 'Bayern Munich', liga: 'Bundesliga' },
  { nombre: 'Borussia Dortmund', liga: 'Bundesliga' },
  { nombre: 'Bayer Leverkusen', liga: 'Bundesliga' },
  { nombre: 'RB Leipzig', liga: 'Bundesliga' },
  { nombre: 'Eintracht Frankfurt', liga: 'Bundesliga' },
  { nombre: 'Borussia Monchengladbach', liga: 'Bundesliga' },
  { nombre: 'Schalke 04', liga: 'Bundesliga' },
  { nombre: 'Hamburgo SV', liga: 'Bundesliga' },
  { nombre: 'VfB Stuttgart', liga: 'Bundesliga' },
  { nombre: 'PSG', liga: 'Ligue 1' },
  { nombre: 'Olympique de Marsella', liga: 'Ligue 1' },
  { nombre: 'Monaco', liga: 'Ligue 1' },
  { nombre: 'Lyon', liga: 'Ligue 1' },
  { nombre: 'Lille', liga: 'Ligue 1' },
  { nombre: 'Ajax', liga: 'Historico' },
  { nombre: 'Porto', liga: 'Historico' },
  { nombre: 'Benfica', liga: 'Historico' },
  { nombre: 'Celtic', liga: 'Historico' },
  { nombre: 'Rangers', liga: 'Historico' },
  { nombre: 'Anderlecht', liga: 'Historico' },
  { nombre: 'Steaua de Bucarest', liga: 'Historico' },
  { nombre: 'Estrella Roja', liga: 'Historico' },
  { nombre: 'Galatasaray', liga: 'Historico' },
  { nombre: 'Fenerbahce', liga: 'Historico' },
  { nombre: 'PSV Eindhoven', liga: 'Historico' },
  { nombre: 'Real Zaragoza', liga: 'Historico' },
  { nombre: 'Deportivo de La Coruna', liga: 'Historico' },
]

// ============================================================
// JUGADORES (actuales e historicos)
// ============================================================
export const JUGADORES = [
  // Porteros actuales
  { nombre: 'Thibaut Courtois', pais: 'Belgica', club: 'Real Madrid', epoca: 'Actual' },
  { nombre: 'Alisson Becker', pais: 'Brasil', club: 'Liverpool', epoca: 'Actual' },
  { nombre: 'Manuel Neuer', pais: 'Alemania', club: 'Bayern Munich', epoca: 'Actual' },
  { nombre: 'Gianluigi Donnarumma', pais: 'Italia', club: 'PSG', epoca: 'Actual' },
  { nombre: 'Marc-Andre ter Stegen', pais: 'Alemania', club: 'Barcelona', epoca: 'Actual' },
  { nombre: 'Unai Simon', pais: 'España', club: 'Athletic Club', epoca: 'Actual' },
  { nombre: 'David Raya', pais: 'España', club: 'Arsenal', epoca: 'Actual' },
  { nombre: 'Yann Sommer', pais: 'Suiza', club: 'Inter de Milan', epoca: 'Actual' },
  { nombre: 'Andre Onana', pais: 'Camerun', club: 'Manchester United', epoca: 'Actual' },
  { nombre: 'Jordan Pickford', pais: 'Inglaterra', club: 'Everton', epoca: 'Actual' },
  { nombre: 'Mike Maignan', pais: 'Francia', club: 'AC Milan', epoca: 'Actual' },
  { nombre: 'Gregor Kobel', pais: 'Suiza', club: 'Borussia Dortmund', epoca: 'Actual' },
  // Defensas actuales
  { nombre: 'Virgil van Dijk', pais: 'Paises Bajos', club: 'Liverpool', epoca: 'Actual' },
  { nombre: 'Ruben Dias', pais: 'Portugal', club: 'Manchester City', epoca: 'Actual' },
  { nombre: 'Marquinhos', pais: 'Brasil', club: 'PSG', epoca: 'Actual' },
  { nombre: 'Dani Carvajal', pais: 'España', club: 'Real Madrid', epoca: 'Actual' },
  { nombre: 'Theo Hernandez', pais: 'Francia', club: 'AC Milan', epoca: 'Actual' },
  { nombre: 'Achraf Hakimi', pais: 'Marruecos', club: 'PSG', epoca: 'Actual' },
  { nombre: 'Antonio Rudiger', pais: 'Alemania', club: 'Real Madrid', epoca: 'Actual' },
  { nombre: 'William Saliba', pais: 'Francia', club: 'Arsenal', epoca: 'Actual' },
  { nombre: 'Pau Cubarsi', pais: 'España', club: 'Barcelona', epoca: 'Actual' },
  { nombre: 'Alejandro Balde', pais: 'España', club: 'Barcelona', epoca: 'Actual' },
  { nombre: 'Eder Militao', pais: 'Brasil', club: 'Real Madrid', epoca: 'Actual' },
  { nombre: 'Dayot Upamecano', pais: 'Francia', club: 'Bayern Munich', epoca: 'Actual' },
  { nombre: 'Ben White', pais: 'Inglaterra', club: 'Arsenal', epoca: 'Actual' },
  { nombre: 'Reece James', pais: 'Inglaterra', club: 'Chelsea', epoca: 'Actual' },
  { nombre: 'Trent Alexander-Arnold', pais: 'Inglaterra', club: 'Liverpool', epoca: 'Actual' },
  { nombre: 'Kyle Walker', pais: 'Inglaterra', club: 'Manchester City', epoca: 'Actual' },
  // Mediocampistas actuales
  { nombre: 'Pedri', pais: 'España', club: 'Barcelona', epoca: 'Actual' },
  { nombre: 'Gavi', pais: 'España', club: 'Barcelona', epoca: 'Actual' },
  { nombre: 'Jude Bellingham', pais: 'Inglaterra', club: 'Real Madrid', epoca: 'Actual' },
  { nombre: 'Kevin De Bruyne', pais: 'Belgica', club: 'Manchester City', epoca: 'Actual' },
  { nombre: 'Martin Odegaard', pais: 'Noruega', club: 'Arsenal', epoca: 'Actual' },
  { nombre: 'Rodri', pais: 'España', club: 'Manchester City', epoca: 'Actual' },
  { nombre: 'Luka Modric', pais: 'Croacia', club: 'Real Madrid', epoca: 'Actual' },
  { nombre: 'Bruno Fernandes', pais: 'Portugal', club: 'Manchester United', epoca: 'Actual' },
  { nombre: 'Frenkie de Jong', pais: 'Paises Bajos', club: 'Barcelona', epoca: 'Actual' },
  { nombre: 'Declan Rice', pais: 'Inglaterra', club: 'Arsenal', epoca: 'Actual' },
  { nombre: 'Granit Xhaka', pais: 'Suiza', club: 'Bayer Leverkusen', epoca: 'Actual' },
  { nombre: 'Florian Wirtz', pais: 'Alemania', club: 'Bayer Leverkusen', epoca: 'Actual' },
  { nombre: 'Jamal Musiala', pais: 'Alemania', club: 'Bayern Munich', epoca: 'Actual' },
  { nombre: 'Federico Valverde', pais: 'Uruguay', club: 'Real Madrid', epoca: 'Actual' },
  { nombre: 'Eduardo Camavinga', pais: 'Francia', club: 'Real Madrid', epoca: 'Actual' },
  { nombre: 'Aurelien Tchouameni', pais: 'Francia', club: 'Real Madrid', epoca: 'Actual' },
  { nombre: 'Vitinha', pais: 'Portugal', club: 'PSG', epoca: 'Actual' },
  { nombre: 'Warren Zaire-Emery', pais: 'Francia', club: 'PSG', epoca: 'Actual' },
  // Delanteros actuales
  { nombre: 'Kylian Mbappe', pais: 'Francia', club: 'Real Madrid', epoca: 'Actual' },
  { nombre: 'Erling Haaland', pais: 'Noruega', club: 'Manchester City', epoca: 'Actual' },
  { nombre: 'Vinicius Jr', pais: 'Brasil', club: 'Real Madrid', epoca: 'Actual' },
  { nombre: 'Lionel Messi', pais: 'Argentina', club: 'Inter Miami', epoca: 'Actual' },
  { nombre: 'Cristiano Ronaldo', pais: 'Portugal', club: 'Al-Nassr', epoca: 'Actual' },
  { nombre: 'Lamine Yamal', pais: 'España', club: 'Barcelona', epoca: 'Actual' },
  { nombre: 'Nico Williams', pais: 'España', club: 'Athletic Club', epoca: 'Actual' },
  { nombre: 'Rodrygo', pais: 'Brasil', club: 'Real Madrid', epoca: 'Actual' },
  { nombre: 'Bukayo Saka', pais: 'Inglaterra', club: 'Arsenal', epoca: 'Actual' },
  { nombre: 'Phil Foden', pais: 'Inglaterra', club: 'Manchester City', epoca: 'Actual' },
  { nombre: 'Rafael Leao', pais: 'Portugal', club: 'AC Milan', epoca: 'Actual' },
  { nombre: 'Marcus Rashford', pais: 'Inglaterra', club: 'Manchester United', epoca: 'Actual' },
  { nombre: 'Harry Kane', pais: 'Inglaterra', club: 'Bayern Munich', epoca: 'Actual' },
  { nombre: 'Antoine Griezmann', pais: 'Francia', club: 'Atletico de Madrid', epoca: 'Actual' },
  { nombre: 'Alvaro Morata', pais: 'España', club: 'AC Milan', epoca: 'Actual' },
  { nombre: 'Dani Olmo', pais: 'España', club: 'Barcelona', epoca: 'Actual' },
  { nombre: 'Mikel Oyarzabal', pais: 'España', club: 'Real Sociedad', epoca: 'Actual' },
  { nombre: 'Ferran Torres', pais: 'España', club: 'Barcelona', epoca: 'Actual' },
  { nombre: 'Ousmane Dembele', pais: 'Francia', club: 'PSG', epoca: 'Actual' },
  { nombre: 'Victor Osimhen', pais: 'Nigeria', club: 'Napoles', epoca: 'Actual' },
  { nombre: 'Khvicha Kvaratskhelia', pais: 'Georgia', club: 'PSG', epoca: 'Actual' },
  { nombre: 'Bernardo Silva', pais: 'Portugal', club: 'Manchester City', epoca: 'Actual' },
  { nombre: 'Diogo Jota', pais: 'Portugal', club: 'Liverpool', epoca: 'Actual' },
  { nombre: 'Darwin Nunez', pais: 'Uruguay', club: 'Liverpool', epoca: 'Actual' },
  { nombre: 'Luis Diaz', pais: 'Colombia', club: 'Liverpool', epoca: 'Actual' },
  { nombre: 'Cole Palmer', pais: 'Inglaterra', club: 'Chelsea', epoca: 'Actual' },
  { nombre: 'Gabriel Martinelli', pais: 'Brasil', club: 'Arsenal', epoca: 'Actual' },
  { nombre: 'Karim Benzema', pais: 'Francia', club: 'Al-Ittihad', epoca: 'Actual' },
  { nombre: 'Robert Lewandowski', pais: 'Polonia', club: 'Barcelona', epoca: 'Actual' },
  { nombre: 'Romelu Lukaku', pais: 'Belgica', club: 'Napoles', epoca: 'Actual' },
  { nombre: 'Son Heung-min', pais: 'Corea del Sur', club: 'Tottenham', epoca: 'Actual' },
  { nombre: 'Mohamed Salah', pais: 'Egipto', club: 'Liverpool', epoca: 'Actual' },
  { nombre: 'Sadio Mane', pais: 'Senegal', club: 'Al-Nassr', epoca: 'Actual' },
  { nombre: 'Lautaro Martinez', pais: 'Argentina', club: 'Inter de Milan', epoca: 'Actual' },
  { nombre: 'Julian Alvarez', pais: 'Argentina', club: 'Atletico de Madrid', epoca: 'Actual' },
  { nombre: 'Enzo Fernandez', pais: 'Argentina', club: 'Chelsea', epoca: 'Actual' },
  // Porteros historicos
  { nombre: 'Iker Casillas', pais: 'España', club: 'Real Madrid', epoca: 'Historico' },
  { nombre: 'Peter Schmeichel', pais: 'Dinamarca', club: 'Manchester United', epoca: 'Historico' },
  { nombre: 'Oliver Kahn', pais: 'Alemania', club: 'Bayern Munich', epoca: 'Historico' },
  { nombre: 'Lev Yashin', pais: 'URSS', club: 'Dynamo Moscu', epoca: 'Historico' },
  { nombre: 'Gianluigi Buffon', pais: 'Italia', club: 'Juventus', epoca: 'Historico' },
  { nombre: 'Edwin van der Sar', pais: 'Paises Bajos', club: 'Manchester United', epoca: 'Historico' },
  // Defensas historicos
  { nombre: 'Franco Baresi', pais: 'Italia', club: 'AC Milan', epoca: 'Historico' },
  { nombre: 'Paolo Maldini', pais: 'Italia', club: 'AC Milan', epoca: 'Historico' },
  { nombre: 'Fabio Cannavaro', pais: 'Italia', club: 'Real Madrid', epoca: 'Historico' },
  { nombre: 'Alessandro Nesta', pais: 'Italia', club: 'AC Milan', epoca: 'Historico' },
  { nombre: 'Roberto Carlos', pais: 'Brasil', club: 'Real Madrid', epoca: 'Historico' },
  { nombre: 'Cafu', pais: 'Brasil', club: 'AC Milan', epoca: 'Historico' },
  { nombre: 'Carles Puyol', pais: 'España', club: 'Barcelona', epoca: 'Historico' },
  { nombre: 'Gerard Pique', pais: 'España', club: 'Barcelona', epoca: 'Historico' },
  { nombre: 'Sergio Ramos', pais: 'España', club: 'Real Madrid', epoca: 'Historico' },
  { nombre: 'Nemanja Vidic', pais: 'Serbia', club: 'Manchester United', epoca: 'Historico' },
  { nombre: 'Rio Ferdinand', pais: 'Inglaterra', club: 'Manchester United', epoca: 'Historico' },
  { nombre: 'John Terry', pais: 'Inglaterra', club: 'Chelsea', epoca: 'Historico' },
  { nombre: 'Ashley Cole', pais: 'Inglaterra', club: 'Chelsea', epoca: 'Historico' },
  { nombre: 'Lilian Thuram', pais: 'Francia', club: 'Juventus', epoca: 'Historico' },
  { nombre: 'Marcel Desailly', pais: 'Francia', club: 'AC Milan', epoca: 'Historico' },
  // Mediocampistas historicos
  { nombre: 'Xavi Hernandez', pais: 'España', club: 'Barcelona', epoca: 'Historico' },
  { nombre: 'Andres Iniesta', pais: 'España', club: 'Barcelona', epoca: 'Historico' },
  { nombre: 'Zinedine Zidane', pais: 'Francia', club: 'Real Madrid', epoca: 'Historico' },
  { nombre: 'Michel Platini', pais: 'Francia', club: 'Juventus', epoca: 'Historico' },
  { nombre: 'Johan Cruyff', pais: 'Paises Bajos', club: 'Barcelona', epoca: 'Historico' },
  { nombre: 'Marco van Basten', pais: 'Paises Bajos', club: 'AC Milan', epoca: 'Historico' },
  { nombre: 'Ruud Gullit', pais: 'Paises Bajos', club: 'AC Milan', epoca: 'Historico' },
  { nombre: 'Frank Rijkaard', pais: 'Paises Bajos', club: 'AC Milan', epoca: 'Historico' },
  { nombre: 'Roy Keane', pais: 'Irlanda', club: 'Manchester United', epoca: 'Historico' },
  { nombre: 'Patrick Vieira', pais: 'Francia', club: 'Arsenal', epoca: 'Historico' },
  { nombre: 'Paul Scholes', pais: 'Inglaterra', club: 'Manchester United', epoca: 'Historico' },
  { nombre: 'Steven Gerrard', pais: 'Inglaterra', club: 'Liverpool', epoca: 'Historico' },
  { nombre: 'Frank Lampard', pais: 'Inglaterra', club: 'Chelsea', epoca: 'Historico' },
  { nombre: 'Michael Ballack', pais: 'Alemania', club: 'Bayern Munich', epoca: 'Historico' },
  { nombre: 'Lothar Matthaus', pais: 'Alemania', club: 'Bayern Munich', epoca: 'Historico' },
  { nombre: 'Andrea Pirlo', pais: 'Italia', club: 'Juventus', epoca: 'Historico' },
  { nombre: 'Gennaro Gattuso', pais: 'Italia', club: 'AC Milan', epoca: 'Historico' },
  { nombre: 'Clarence Seedorf', pais: 'Paises Bajos', club: 'AC Milan', epoca: 'Historico' },
  { nombre: 'Kaka', pais: 'Brasil', club: 'AC Milan', epoca: 'Historico' },
  { nombre: 'Rivaldo', pais: 'Brasil', club: 'Barcelona', epoca: 'Historico' },
  { nombre: 'Luis Figo', pais: 'Portugal', club: 'Real Madrid', epoca: 'Historico' },
  { nombre: 'Riquelme', pais: 'Argentina', club: 'Boca Juniors', epoca: 'Historico' },
  { nombre: 'Juan Roman Riquelme', pais: 'Argentina', club: 'Boca Juniors', epoca: 'Historico' },
  { nombre: 'Wesley Sneijder', pais: 'Paises Bajos', club: 'Inter de Milan', epoca: 'Historico' },
  { nombre: 'Xabi Alonso', pais: 'España', club: 'Real Madrid', epoca: 'Historico' },
  { nombre: 'Claude Makelele', pais: 'Francia', club: 'Real Madrid', epoca: 'Historico' },
  { nombre: 'David Beckham', pais: 'Inglaterra', club: 'Manchester United', epoca: 'Historico' },
  // Delanteros historicos
  { nombre: 'Pele', pais: 'Brasil', club: 'Santos', epoca: 'Historico' },
  { nombre: 'Diego Maradona', pais: 'Argentina', club: 'Napoles', epoca: 'Historico' },
  { nombre: 'Ronaldo Nazario', pais: 'Brasil', club: 'Real Madrid', epoca: 'Historico' },
  { nombre: 'Ronaldinho', pais: 'Brasil', club: 'Barcelona', epoca: 'Historico' },
  { nombre: 'Garrincha', pais: 'Brasil', club: 'Botafogo', epoca: 'Historico' },
  { nombre: 'Thierry Henry', pais: 'Francia', club: 'Arsenal', epoca: 'Historico' },
  { nombre: 'Ruud van Nistelrooy', pais: 'Paises Bajos', club: 'Real Madrid', epoca: 'Historico' },
  { nombre: 'Raul Gonzalez', pais: 'España', club: 'Real Madrid', epoca: 'Historico' },
  { nombre: 'Fernando Torres', pais: 'España', club: 'Liverpool', epoca: 'Historico' },
  { nombre: 'David Villa', pais: 'España', club: 'Barcelona', epoca: 'Historico' },
  { nombre: 'Didier Drogba', pais: 'Costa de Marfil', club: 'Chelsea', epoca: 'Historico' },
  { nombre: 'Filippo Inzaghi', pais: 'Italia', club: 'AC Milan', epoca: 'Historico' },
  { nombre: 'Alessandro Del Piero', pais: 'Italia', club: 'Juventus', epoca: 'Historico' },
  { nombre: 'Francesco Totti', pais: 'Italia', club: 'AS Roma', epoca: 'Historico' },
  { nombre: 'Andriy Shevchenko', pais: 'Ucrania', club: 'AC Milan', epoca: 'Historico' },
  { nombre: 'Arjen Robben', pais: 'Paises Bajos', club: 'Bayern Munich', epoca: 'Historico' },
  { nombre: 'Franck Ribery', pais: 'Francia', club: 'Bayern Munich', epoca: 'Historico' },
  { nombre: 'Romario', pais: 'Brasil', club: 'Barcelona', epoca: 'Historico' },
  { nombre: 'Bebeto', pais: 'Brasil', club: 'Vasco da Gama', epoca: 'Historico' },
  { nombre: 'Roberto Baggio', pais: 'Italia', club: 'Juventus', epoca: 'Historico' },
  { nombre: 'George Best', pais: 'Irlanda del Norte', club: 'Manchester United', epoca: 'Historico' },
  { nombre: 'Bobby Charlton', pais: 'Inglaterra', club: 'Manchester United', epoca: 'Historico' },
  { nombre: 'Gary Lineker', pais: 'Inglaterra', club: 'Barcelona', epoca: 'Historico' },
  { nombre: 'Alan Shearer', pais: 'Inglaterra', club: 'Newcastle', epoca: 'Historico' },
  { nombre: 'Wayne Rooney', pais: 'Inglaterra', club: 'Manchester United', epoca: 'Historico' },
  { nombre: 'Michael Owen', pais: 'Inglaterra', club: 'Liverpool', epoca: 'Historico' },
  { nombre: 'Paul Gascoigne', pais: 'Inglaterra', club: 'Tottenham', epoca: 'Historico' },
  { nombre: 'Gerd Muller', pais: 'Alemania', club: 'Bayern Munich', epoca: 'Historico' },
  { nombre: 'Karl-Heinz Rummenigge', pais: 'Alemania', club: 'Bayern Munich', epoca: 'Historico' },
  { nombre: 'Miroslav Klose', pais: 'Alemania', club: 'Bayern Munich', epoca: 'Historico' },
  { nombre: 'Eusebio', pais: 'Portugal', club: 'Benfica', epoca: 'Historico' },
  { nombre: 'Gabriel Batistuta', pais: 'Argentina', club: 'Fiorentina', epoca: 'Historico' },
  { nombre: 'Franz Beckenbauer', pais: 'Alemania', club: 'Bayern Munich', epoca: 'Historico' },
  { nombre: 'Eric Cantona', pais: 'Francia', club: 'Manchester United', epoca: 'Historico' },
  { nombre: 'Hristo Stoichkov', pais: 'Bulgaria', club: 'Barcelona', epoca: 'Historico' },
  { nombre: 'Dennis Bergkamp', pais: 'Paises Bajos', club: 'Arsenal', epoca: 'Historico' },
  { nombre: 'Patrick Kluivert', pais: 'Paises Bajos', club: 'Barcelona', epoca: 'Historico' },
  { nombre: 'Zlatan Ibrahimovic', pais: 'Suecia', club: 'PSG', epoca: 'Historico' },
  { nombre: 'Henrik Larsson', pais: 'Suecia', club: 'Celtic', epoca: 'Historico' },
  { nombre: 'Davor Suker', pais: 'Croacia', club: 'Real Madrid', epoca: 'Historico' },
  { nombre: 'Thomas Muller', pais: 'Alemania', club: 'Bayern Munich', epoca: 'Historico' },
  { nombre: 'Eden Hazard', pais: 'Belgica', club: 'Chelsea', epoca: 'Historico' },
  { nombre: 'Vincent Kompany', pais: 'Belgica', club: 'Manchester City', epoca: 'Historico' },
  { nombre: 'Park Ji-sung', pais: 'Corea del Sur', club: 'Manchester United', epoca: 'Historico' },
  { nombre: 'Hidetoshi Nakata', pais: 'Japon', club: 'AS Roma', epoca: 'Historico' },
  { nombre: 'Samuel Eto', pais: 'Camerun', club: 'Barcelona', epoca: 'Historico' },
  { nombre: 'Roger Milla', pais: 'Camerun', club: 'Montpellier', epoca: 'Historico' },
  { nombre: 'Nwankwo Kanu', pais: 'Nigeria', club: 'Arsenal', epoca: 'Historico' },
  { nombre: 'Hugo Sanchez', pais: 'Mexico', club: 'Real Madrid', epoca: 'Historico' },
  { nombre: 'Ivan Zamorano', pais: 'Chile', club: 'Real Madrid', epoca: 'Historico' },
]

// Helper
export const getItems = (categoria) => {
  switch(categoria) {
    case 'selecciones': return SELECCIONES.map(s => ({ ...s, display: s.nombre, sub: s.grupo }))
    case 'clubes': return CLUBES.map(c => ({ ...c, display: c.nombre, sub: c.liga }))
    case 'jugadores': return JUGADORES.map(j => ({ ...j, display: j.nombre, sub: j.club + ' - ' + j.epoca }))
    default: return []
  }
}
